### ISSUE TITLE
No compile in ios and

### ISSUE THREAD

**Issue by RicardoBer** [alexszilagyi/cordova-HTTP#2]
Hello, I installed main branch (wymsee) and then replace with your fork.

**First and most important question, How can I install directly your fork?.**

I have a lot of troubles installing, If I install wymsee too, no copy to platforms, some time fails on install, on add platform, etc) 

In java I must change a lot, the cancelling method raise an ioexception, perhaps beacause no close streams, well I can run well now.

But in ios it no compile.

1.- I must comment #import <Cordova/CDVJSON.h> in CordovaPlugin.h

2.- change path to CDVFile.h

3.- Now I have this error in linker
  Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_HttpManager", referenced from:
      objc-class-ref in CordovaHttpPlugin.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

4.- Another error:
Showing Recent Issues clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can you help me?

Thanks in advance

**Comment by RicardoBer** [comment]
I answer to my self.
The first one work adding the files not present in wymsee repo.

I can't figure solution to second error.

**Comment by RicardoBer** [comment]
I answer to my questions

First one You must add all files not present in wymsee to your project

Second One, you must go to Project, "Build Phases" and clean from failing files.

**Comment by alexszilagyi** [comment]
@RicardoBer : as you can see [in this commit](https://github.com/alexszilagyi/cordova-HTTP/commit/4ab1079215ee153dd3aedca7ba418a41574da018) I have removed the iOS platform since in my case would not be needed, please make sure you've cloned the right repo 😄

**Comment by RicardoBer** [comment]
Ok, thanks.

I make IOS work as spected, timer set fixed to 30 seconds and invalidateSessionCancelingTasks works.

I android I set a fixed timer of 30s too, because in android it gets infinite, and catch IOException (not avoid the exception I'm afraid) whem call invalidateSessionCancelingTasks.

If there are some one interested, I don't wank to make a fork.

Many thanks alexszilagyi and original repo developers, whitout your work I will be in very big trouble.
